movies/urls.py
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static


app_name = 'movies'

urlpatterns = [

    path('<str:name>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('<str:name>/add_review/', views.AddReviewView.as_view(), name='add_review'),
    path('<str:name>/like_movie/', views.AddLikeMovieView.as_view(), name='like_movie'),
    path('<str:name>/want_to_watch/', views.AddWantToWatchView.as_view(), name='want_to_watch'),
    path('<str:name>/add_to_list/', views.AddMovieToList.as_view(), name='add_to_list'),
    path('<str:name>/delete_like/', views.DeleteLikedMovieView.as_view(), name='delete_like'),
    path('<str:name>/delete_from_watchlist/', views.DeleteWantToWatchMovieView.as_view(), name='delete_from_watchlist'),
    path('<str:name>/director/', views.DirectorDetailView.as_view(), name='director_detail'),
    path('<str:name>/genre/', views.GenreDetailView.as_view(), name='genre_detail'),
    path('<str:name>/delete_from_watched/', views.DeleteWatchedMovieView.as_view(), name='delete_from_watched'),
    path('<str:name>/add_watched/', views.AddWatchedMovieView.as_view(), name='add_watched'),
    path('<str:name>/delete_review/', views.DeleteReviewView.as_view(), name='delete_review'),
    path('<int:review_id>/review_detail/', views.ReviewDetailView.as_view(), name='review_detail')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile_update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('profile/details/<str:username>/', views.ProfileView.as_view(), name='profile'),
    path('liked_movies/<str:username>/', views.LikedMovieView.as_view(), name='liked_movies'),
    path('watchlist/<str:username>/', views.WatchListView.as_view(), name='watchlist'),
    path('profile/create_new_list/', views.CreateListView.as_view(), name='create_new_list'),
    path('list_details/<int:list_id>/<str:username>/', views.CustomListView.as_view(), name='custom_list'),
    path('all_lists/<str:username>/', views.SeeAllListsView.as_view(), name='all_lists'),
    path('all_reviews/<str:username>/', views.AllReviewsView.as_view(), name='all_reviews'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('delete_movie/<int:list_id>/', views.DeleteMovieFromList.as_view(), name='delete_movie'),
    path('follow/<str:username>/', views.FollowUserView.as_view(), name='follow'),
    path('unfollow/<str:username>/', views.UnfollowUserView.as_view(), name='unfollow'),
    path('all_followers/<str:username>/', views.AllFollowersView.as_view(), name='all_followers'),
    path('all_followings/<str:username>/', views.AllFollowingsView.as_view(), name='all_followings'),
    path('delete_follower/', views.DeleteFollowerView.as_view(), name='delete_follower'),
    path('watched_movies/<str:username>/', views.WatchedMoviesView.as_view(), name='watched_movies'),
    path('delete_review/', views.ProfileDeleteReviewView.as_view(), name='delete_review'),
    path('review_detail/<int:review_id>/', views.ReviewDetailView.as_view(), name='review_detail'),
    path('delete_list/', views.DeleteListView.as_view(), name='delete_list'),
    path('unfollow_from_profile/<str:username>/', views.ProfileUnfollowUserView.as_view(), name='unfollow_from_profile')
    ,
    path('movies_of_year/<int:year>/', views.MoviesOfYearView.as_view(), name='movies_of_year'),
    path('most_liked_movies/', views.MostLikedMoviesView.as_view(), name='most_liked_movies'),
    path('friends_watched_recently/', views.FriendsWatchedRecentlyView.as_view(), name='friends_watched_recently'),
    path('recommended_movies/', views.RecommendedMoviesView.as_view(), name='recommended_movies'),
    path('similar_users/', views.SimilarUsersView.as_view(), name='similar_users'),
    path('all_genres/', views.AllGenresView.as_view(), name='all_genres'),
    path('add_list_like/<int:list_id>/', views.AddListLikeView.as_view(), name='add_list_like'),
    path('delete_list_like/<int:list_id>/', views.DeleteListLikeView.as_view(), name='delete_list_like'),
    path('favourite_lists/<str:username>/', views.FavouriteListsView.as_view(), name='favourite_lists'),
    path('watched_movies/<str:username>/<int:year>/', views.WatchedMoviesView.as_view(), name='watched_movies'),
    path('all_reviews/<str:username>/<int:year>/', views.AllReviewsView.as_view(), name='all_reviews'),
    path('liked_movies/<str:username>/<int:year>', views.LikedMovieView.as_view(), name='liked_movies'),
    path('make_public/<int:list_id>/<str:username>/', views.MakeListPublicView.as_view(), name='make_public'),
    path('make_private/<int:list_id>/<str:username>/', views.MakeListPrivateView.as_view(), name='make_private'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/models.py
from django.db import models
from django.utils import timezone
import datetime
from users.models import User
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.
class Director(models.Model):
    name = models.CharField(max_length=255)
    birth_year = models.IntegerField(null=True, blank=True)
    bio = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255, unique=True)
    year = models.IntegerField()
    pub_date = models.DateTimeField('date published', default=timezone.now)
    duration = models.IntegerField(default=0)
    director = models.ForeignKey(Director, on_delete=models.CASCADE)
    poster = models.ImageField(upload_to="movie_posters", default='poster.jpg')
    genre = models.ManyToManyField(Genre, blank=True)
    synopsis = models.TextField(blank=True)
    likes = models.IntegerField(default=0)
    trailer_id = models.CharField(max_length=255, blank=True, null=True)

    def get_avg_rating(self):
        if self.review_set.count() > 0:
            return "{:.1f}".format(self.review_set.aggregate(models.Avg('rating')).get('rating__avg'))
        else:
            return 0

    def come_out_this_year(self):
        now = timezone.now()
        return now.year == self.year

    def __str__(self):
        return self.title


class Actor(models.Model):
    name = models.CharField(max_length=255)
    age = models.IntegerField()
    movies = models.ManyToManyField(Movie)

    def __str__(self):
        return self.name


class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    review = models.TextField()
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    review_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.review

movies/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm

from django import forms
from .models import Movie, Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'review']
        widgets = {
            'rating': forms.NumberInput(attrs={'class': 'form-control',
                                               'placeholder': 'Give a rating (integer) to this movie between 1 and 10'})
            , 'review': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'placeholder': 'Enter a review'}),
        }

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import messages

from .forms import ReviewForm
from .models import Movie, Director, Genre, Review
from django.db.models import F
from users.models import User, LikedMovie, WantToWatchMovie, ElementOfList, ListName, WatchedMovie
from django.core.paginator import Paginator

# Create your views here.


class MovieDetailView(View):
    def get(self, request, name):
        movie = get_object_or_404(Movie, title=name)
        if request.user.is_authenticated:
            user_lists = ListName.objects.filter(user=request.user)
            liked = LikedMovie.objects.filter(movie=movie, user=request.user).exists()
            want_to_watch = WantToWatchMovie.objects.filter(movie=movie, user=request.user).exists()
            watched = WatchedMovie.objects.filter(movie=movie, user=request.user).exists()
        else:
            user_lists = []
            liked = False
            want_to_watch = False
            watched = False
        paginator = Paginator(movie.review_set.all().order_by('-review_date'), 5)
        page_number = request.GET.get('page')
        reviews = paginator.get_page(page_number)
        avg_rating = movie.get_avg_rating()
        return render(request, 'movies/movie_detail.html', {'movie': movie, 'user_lists': user_lists,
                                                            'liked': liked, 'want_to_watch': want_to_watch,
                                                            'watched': watched, "avg_rating": avg_rating,
                                                            'reviews': reviews})


@method_decorator(login_required, name='dispatch')
class AddReviewView(View):
    def get(self, request, name):
        movie = get_object_or_404(Movie, title=name)
        form = ReviewForm()
        return render(request, 'movies/add_review.html', {'movie': movie, 'form': form})

    def post(self, request, name):
        movie = get_object_or_404(Movie, title=name)
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            # we didn't save to database now because we'll also add movie and writer
            review.movie = movie
            review.writer = request.user
            review.save()
            messages.success(request, 'Your review has been added.')
            return HttpResponseRedirect(reverse('movies:movie_detail', args=[movie.title]))
        else:
            messages.error(request, 'Error, please add the review again.')
            return HttpResponseRedirect(reverse('movies:add_review', args=[movie.title]))


class AddLikeMovieView(View):
    def post(self, request, name):
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'You are not authenticated'}, status=401)

        movie = get_object_or_404(Movie, title=name)
        if not LikedMovie.objects.filter(user=request.user, movie=movie).exists():
            liked_movie = LikedMovie(user=request.user, movie=movie)
            liked_movie.save()
            movie.likes = F("likes") + 1
            movie.save()

        return JsonResponse({
            'status': 'liked',
            'unlike_url': reverse('movies:delete_like', args=[movie.title]),
            'message': f'You liked {movie.title}.',
        })


class AddWantToWatchView(View):
    def post(self, request, name):
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'You are not authenticated'}, status=401)

        movie = get_object_or_404(Movie, title=name)
        if not WantToWatchMovie.objects.filter(user=request.user, movie=movie).exists():
            want_movie = WantToWatchMovie(user=request.user, movie=movie)
            want_movie.save()

        return JsonResponse({
            'status': 'want_to_watch',
            'delete_want_to_url': reverse('movies:delete_from_watchlist', args=[movie.title]),
            'message': f'{movie.title} is added to watchlist.',
        })


@method_decorator(login_required, name='dispatch')
class AddMovieToList(View):
    def post(self, request, name):
        movie = get_object_or_404(Movie, title=name)
        try:
            selected_list = ListName.objects.get(id=request.POST['list_id'], user=request.user)
        except (KeyError, ListName.DoesNotExist):
            return render(
                request,
                "movies/movie_detail.html",
                {
                    "movie": movie,
                    "user_lists": ListName.objects.filter(user=request.user),
                },
            )
        else:
            if not ElementOfList.objects.filter(list_name=selected_list, movie=movie, user=request.user).exists():
                new_element = ElementOfList(movie=movie, list_name=selected_list, user=request.user)
                new_element.save()
                selected_list.save()
            return HttpResponseRedirect(reverse("movies:movie_detail", args=[movie.title]))


class DeleteLikedMovieView(View):
    def post(self, request, name):
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'You are not authenticated'}, status=401)

        movie = get_object_or_404(Movie, title=name)
        if LikedMovie.objects.filter(user=request.user, movie=movie).exists():
            liked_movie = LikedMovie.objects.get(user=request.user, movie=movie)
            liked_movie.delete()
            movie.likes = F("likes") - 1
            movie.save()

        return JsonResponse({
            'status': 'unliked',
            'like_url': reverse('movies:like_movie', args=[movie.title]),
            'message': f'You unliked {movie.title}.',
        })


class DeleteWantToWatchMovieView(View):
    def post(self, request, name):
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'You are not authenticated'}, status=401)

        movie = get_object_or_404(Movie, title=name)
        if WantToWatchMovie.objects.filter(user=request.user, movie=movie).exists():
            want_movie = WantToWatchMovie.objects.get(user=request.user, movie=movie)
            want_movie.delete()

        return JsonResponse({
            'status': 'not_want_to_watch',
            'add_want_to_url': reverse('movies:want_to_watch', args=[movie.title]),
            'message': f'{movie.title} is deleted from watchlist.',
        })


class DirectorDetailView(View):
    def get(self, request, name):
        director = get_object_or_404(Director, name=name)
        movies = Movie.objects.filter(director=director).order_by('year')
        return render(request, 'movies/director_detail.html', {'movies': movies, 'director': director})


class GenreDetailView(View):
    def get(self, request, name):
        genre = get_object_or_404(Genre, name=name)
        paginator = Paginator(genre.movie_set.all().order_by('title'), 24)
        page_number = request.GET.get('page')
        movies = paginator.get_page(page_number)
        return render(request, 'movies/genre_detail.html', {'movies': movies, 'genre': genre})


class AddWatchedMovieView(View):
    def post(self, request, name):
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'You are not authenticated'}, status=401)

        movie = get_object_or_404(Movie, title=name)
        if not WatchedMovie.objects.filter(user=request.user, movie=movie).exists():
            watched_movie = WatchedMovie(user=request.user, movie=movie)
            watched_movie.save()

        return JsonResponse({
            'status': 'watched',
            'delete_watched_url': reverse('movies:delete_from_watched', args=[movie.title]),
            'message': f'{movie.title} is marked as watched.',
        })


class DeleteWatchedMovieView(View):
    def post(self, request, name):
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'You are not authenticated'}, status=401)

        movie = get_object_or_404(Movie, title=name)
        if WatchedMovie.objects.filter(user=request.user, movie=movie).exists():
            watched_movie = WatchedMovie.objects.get(user=request.user, movie=movie)
            watched_movie.delete()

        return JsonResponse({
            'status': 'not_watched',
            'add_watched_url': reverse('movies:add_watched', args=[movie.title]),
            'message': f'{movie.title} is deleted from watched movies.',
        })


@method_decorator(login_required, name='dispatch')
class DeleteReviewView(View):
    def post(self, request, name):
        movie = get_object_or_404(Movie, title=name)
        try:
            selected_review = Review.objects.get(pk=request.POST['review_id'], writer=request.user, movie=movie)
        except (KeyError, Review.DoesNotExist):
            messages.error(request, "Review does not exist.")
            return HttpResponseRedirect(reverse('movies:movie_detail', args=[name]))
        else:
            selected_review.delete()
            messages.success(request, "Review has been deleted.")
            return HttpResponseRedirect(reverse('movies:movie_detail', args=[name]))


class ReviewDetailView(View):
    def get(self, request, review_id):
        review = get_object_or_404(Review, pk=review_id)
        movie = review.movie
        writer = review.writer
        return render(request, 'movies/review_detail.html', {'review': review, 'movie': movie, 'writer': writer})

movies/templates/movies/add_review.html
{% extends "users/base.html" %}

{% block title %}Add New Review to {{ movie.title }}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Add New Review for {{ movie.title }}</h1>

    {% if messages %}
        <div class="alert alert-info">
            <ul class="mb-0">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <form method="POST" class="bg-light-subtle p-4 rounded border border-dark">
        {% csrf_token %}

        <div class="mb-3">
            <label for="{{ form.rating.id_for_label }}" class="form-label">Rating:</label>
            {{ form.rating }}
        </div>

        <div class="mb-3">
            <label for="{{ form.review.id_for_label }}" class="form-label">Review:</label>
            {{ form.review }}
        </div>

        <button type="submit" class="btn btn-primary">Add Review</button>
        <a href="{% url 'movies:movie_detail' movie.title %}" class="btn btn-secondary ms-2">Go back to movie detail page</a>
    </form>
</div>
{% endblock %}

movies/templates/movies/director_detail.html
{% extends "users/base.html" %}

{% block title %}{{ director.name }}{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <!-- Director Details -->
        <div class="col-md-4 mb-4">
            <div class="card border-dark">
                <div class="card-body text-center">
                    <h3 class="card-title">{{ director.name }}</h3>
                    <p class="card-text"><strong>Birth Year:</strong> {{ director.birth_year }}</p>
                    <p class="card-text"><strong>Bio:</strong> {{ director.bio|default:"No bio available." }}</p>
                </div>
            </div>
        </div>

        <!-- Director's Movies -->
        <div class="col-md-8">
            <div class="card border-dark mb-4">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4>Movies Directed</h4>
                </div>
                <div class="card-body">
                    {% if movies %}
                        <div class="row">
                            {% for movie in movies %}
                                <div class="col-md-3 mb-3">
                                    <div class="card bg-dark text-light border-dark card-custom">
                                        <a href="{% url 'movies:movie_detail' movie.title %}">
                                            <img src="{{ movie.poster.url }}" class="card-img-top" alt="{{ movie.title }} Poster">
                                        </a>
                                        <div class="card-body text-center">
                                            <h5 class="card-title">{{ movie.title }}</h5>
                                            <p class="card-text">{{ movie.year }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <p>No movies directed yet.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

movies/templates/movies/genre_detail.html
{% extends "users/base.html" %}

{% block title %}{{ genre.name }}{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">

        <!-- Movies -->
        <div class="col-md-12">
            <div class="card border-dark mb-4">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4>{{ genre.name }} Movies</h4>
                    <!-- Pagination Controls (Top) -->
                    <nav aria-label="Page navigation">
                        <ul class="pagination mb-0">
                            {% if movies.has_previous %}
                                <li class="page-item">
                                    <a class="page-link btn btn-secondary" href="?page=1" aria-label="First">
                                        <span aria-hidden="true">&laquo;&laquo;</span>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link btn btn-secondary" href="?page={{ movies.previous_page_number }}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <span class="page-link btn btn-secondary">&laquo;&laquo;</span>
                                </li>
                                <li class="page-item disabled">
                                    <span class="page-link btn btn-secondary">&laquo;</span>
                                </li>
                            {% endif %}

                            <li class="page-item disabled">
                                <span class="page-link btn btn-secondary">Page {{ movies.number }} of {{ movies.paginator.num_pages }}</span>
                            </li>

                            {% if movies.has_next %}
                                <li class="page-item">
                                    <a class="page-link btn btn-secondary" href="?page={{ movies.next_page_number }}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link btn btn-secondary" href="?page={{ movies.paginator.num_pages }}" aria-label="Last">
                                        <span aria-hidden="true">&raquo;&raquo;</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <span class="page-link btn btn-secondary">&raquo;</span>
                                </li>
                                <li class="page-item disabled">
                                    <span class="page-link btn btn-secondary">&raquo;&raquo;</span>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                <div class="card-body">
                    {% if movies %}
                        <div class="row">
                            {% for movie in movies %}
                                <div class="col-md-2 mb-3">
                                    <div class="card bg-dark text-light border-dark card-custom">
                                        <a href="{% url 'movies:movie_detail' movie.title %}">
                                            <img src="{{ movie.poster.url }}" class="card-img-top" alt="{{ movie.title }} Poster">
                                        </a>
                                        <div class="card-body text-center">
                                            <h5 class="card-title">{{ movie.title }}</h5>
                                            <p class="card-text">{{ movie.year }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <p>No {{ genre.name }} movies yet.</p>
                    {% endif %}
                </div>

                <!-- Pagination Controls (Bottom) -->
                <div class="d-flex justify-content-end mt-4" style="margin-bottom: 20px; padding-right: 15px;">
                    <nav aria-label="Page navigation">
                        <ul class="pagination mb-0">
                            {% if movies.has_previous %}
                                <li class="page-item">
                                    <a class="page-link btn btn-secondary" href="?page=1" aria-label="First">
                                        <span aria-hidden="true">&laquo;&laquo;</span>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link btn btn-secondary" href="?page={{ movies.previous_page_number }}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <span class="page-link btn btn-secondary">&laquo;&laquo;</span>
                                </li>
                                <li class="page-item disabled">
                                    <span class="page-link btn btn-secondary">&laquo;</span>
                                </li>
                            {% endif %}

                            <li class="page-item disabled">
                                <span class="page-link btn btn-secondary">Page {{ movies.number }} of {{ movies.paginator.num_pages }}</span>
                            </li>

                            {% if movies.has_next %}
                                <li class="page-item">
                                    <a class="page-link btn btn-secondary" href="?page={{ movies.next_page_number }}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link btn btn-secondary" href="?page={{ movies.paginator.num_pages }}" aria-label="Last">
                                        <span aria-hidden="true">&raquo;&raquo;</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <span class="page-link btn btn-secondary">&raquo;</span>
                                </li>
                                <li class="page-item disabled">
                                    <span class="page-link btn btn-secondary">&raquo;&raquo;</span>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

movies/templates/movies/review_detail.html
{% extends "users/base.html" %}

{% block title %}Review for {{ movie.title }}{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <!-- Movie Poster -->
        <div class="col-md-4 mb-4">
            <div class="card border-dark">
                <img src="{{ movie.poster.url }}" class="card-img-top" alt="{{ movie.title }} Poster">
            </div>
        </div>

        <!-- Review Details -->
        <div class="col-md-8">
            <div class="card border-dark bg-dark text-light mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ movie.title }}</h2>
                    <p class="card-text"><strong>By:</strong> <a href="{% url 'users:profile' writer.username %}" class="btn btn-sm btn-outline-primary p-1" role="button">{{ writer.username }}</a> , added on {{ review.review_date.date }}</p>
                    <p class="card-text"><strong>Score:</strong> {{ review.rating }}</p>
                    <p class="card-text"><strong>Review:</strong> {{ review.review }}</p>

                    <!-- Conditional Delete Button -->
                    {% if request.user.is_authenticated and writer == request.user %}
                        <form action="{% url 'movies:delete_review' movie.title %}" method="post" class="mt-2">
                            {% csrf_token %}
                            <input type="hidden" name="review_id" value="{{ review.id }}">
                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this review?');">Delete Review</button>
                        </form>
                    {% endif %}

                    <!-- Link to Movie Detail -->
                    <a href="{% url 'movies:movie_detail' movie.title %}" class="btn btn-secondary mt-2">Back to Movie Details</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}