movies/urls.py
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static


app_name = 'movies'

urlpatterns = [

    path('<str:name>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('<str:name>/add_review/', views.AddReviewView.as_view(), name='add_review'),
    path('<str:name>/like_movie/', views.AddLikeMovieView.as_view(), name='like_movie'),
    path('<str:name>/want_to_watch/', views.AddWantToWatchView.as_view(), name='want_to_watch'),
    path('<str:name>/add_to_list/', views.AddMovieToList.as_view(), name='add_to_list'),
    path('<str:name>/delete_like/', views.DeleteLikedMovieView.as_view(), name='delete_like'),
    path('<str:name>/delete_from_watchlist/', views.DeleteWantToWatchMovieView.as_view(), name='delete_from_watchlist'),
    path('<str:name>/director/', views.DirectorDetailView.as_view(), name='director_detail'),
    path('<str:name>/genre/', views.GenreDetailView.as_view(), name='genre_detail'),
    path('<str:name>/delete_from_watched/', views.DeleteWatchedMovieView.as_view(), name='delete_from_watched'),
    path('<str:name>/add_watched/', views.AddWatchedMovieView.as_view(), name='add_watched'),
    path('<str:name>/delete_review/', views.DeleteReviewView.as_view(), name='delete_review'),
    path('<int:review_id>/review_detail/', views.ReviewDetailView.as_view(), name='review_detail')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile_update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('profile/details/<str:username>/', views.ProfileView.as_view(), name='profile'),
    path('liked_movies/<str:username>/', views.LikedMovieView.as_view(), name='liked_movies'),
    path('watchlist/<str:username>/', views.WatchListView.as_view(), name='watchlist'),
    path('profile/create_new_list/', views.CreateListView.as_view(), name='create_new_list'),
    path('list_details/<int:list_id>/<str:username>/', views.CustomListView.as_view(), name='custom_list'),
    path('all_lists/<str:username>/', views.SeeAllListsView.as_view(), name='all_lists'),
    path('all_reviews/<str:username>/', views.AllReviewsView.as_view(), name='all_reviews'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('delete_movie/<int:list_id>/', views.DeleteMovieFromList.as_view(), name='delete_movie'),
    path('follow/<str:username>/', views.FollowUserView.as_view(), name='follow'),
    path('unfollow/<str:username>/', views.UnfollowUserView.as_view(), name='unfollow'),
    path('all_followers/<str:username>/', views.AllFollowersView.as_view(), name='all_followers'),
    path('all_followings/<str:username>/', views.AllFollowingsView.as_view(), name='all_followings'),
    path('delete_follower/', views.DeleteFollowerView.as_view(), name='delete_follower'),
    path('watched_movies/<str:username>/', views.WatchedMoviesView.as_view(), name='watched_movies'),
    path('delete_review/', views.ProfileDeleteReviewView.as_view(), name='delete_review'),
    path('review_detail/<int:review_id>/', views.ReviewDetailView.as_view(), name='review_detail'),
    path('delete_list/', views.DeleteListView.as_view(), name='delete_list'),
    path('unfollow_from_profile/<str:username>/', views.ProfileUnfollowUserView.as_view(), name='unfollow_from_profile')
    ,
    path('movies_of_year/<int:year>/', views.MoviesOfYearView.as_view(), name='movies_of_year'),
    path('most_liked_movies/', views.MostLikedMoviesView.as_view(), name='most_liked_movies'),
    path('friends_watched_recently/', views.FriendsWatchedRecentlyView.as_view(), name='friends_watched_recently'),
    path('recommended_movies/', views.RecommendedMoviesView.as_view(), name='recommended_movies'),
    path('similar_users/', views.SimilarUsersView.as_view(), name='similar_users'),
    path('all_genres/', views.AllGenresView.as_view(), name='all_genres'),
    path('add_list_like/<int:list_id>/', views.AddListLikeView.as_view(), name='add_list_like'),
    path('delete_list_like/<int:list_id>/', views.DeleteListLikeView.as_view(), name='delete_list_like'),
    path('favourite_lists/<str:username>/', views.FavouriteListsView.as_view(), name='favourite_lists'),
    path('watched_movies/<str:username>/<int:year>/', views.WatchedMoviesView.as_view(), name='watched_movies'),
    path('all_reviews/<str:username>/<int:year>/', views.AllReviewsView.as_view(), name='all_reviews'),
    path('liked_movies/<str:username>/<int:year>', views.LikedMovieView.as_view(), name='liked_movies'),
    path('make_public/<int:list_id>/<str:username>/', views.MakeListPublicView.as_view(), name='make_public'),
    path('make_private/<int:list_id>/<str:username>/', views.MakeListPrivateView.as_view(), name='make_private'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm

from users.models import Profile, ListName
from django import forms


class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'image']


class NewListForm(ModelForm):
    class Meta:
        model = ListName
        fields = ['name', 'is_private']
        labels = {
            'is_private': "Do you want this list to be private?"
        }

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import messages

from movies.models import Movie, Review, Director, Genre
from users.forms import UserUpdateForm, ProfileUpdateForm, NewListForm
from users.models import LikedMovie, WantToWatchMovie, ListName, ElementOfList, Following, WatchedMovie, LikedList
from django.contrib.auth.models import User
from django.db.models import F
from django.utils import timezone
import datetime
from movies.search.search import MovieDocument, DirectorDocument, GenreDocument, UserDocument, ListDocument
from elasticsearch_dsl import Q
from django.core.paginator import Paginator
from .recommendations import recommend_movies_for_user, recommend_friends_for_user


class HomeView(View):
    def get(self, request):
        # movies = Movie.objects.all()
        now = timezone.now()
        most_liked_movies = Movie.objects.order_by('-likes', 'title')[:6]
        movies_of_this_year = Movie.objects.filter(year=now.year).order_by('-pub_date', 'title')[:6]

        if request.user.is_authenticated:
            movies_of_friends = request.user.profile.get_last_watched()[:6]
            recommendations = recommend_movies_for_user(request.user)[:6]
            similar_users = list(User.objects.filter(id__in=recommend_friends_for_user(request.user)))[:6]
            no_reviews = not Review.objects.filter(writer=request.user).exists()
        else:
            movies_of_friends = []
            recommendations = []
            similar_users = []
            no_reviews = True

        return render(request, "users/home.html", {"movies_of_this_year": movies_of_this_year,
                                                   "most_liked_movies": most_liked_movies,
                                                   "movies_of_friends": movies_of_friends,
                                                   "recommendations": recommendations,
                                                   "similar_users": similar_users,
                                                   'year': now.year, 'no_reviews': no_reviews})


class RegisterView(View):
    def get(self, request, *args, **kwargs):
        form = UserCreationForm()
        return render(request, "users/register.html", {'form': form})

    def post(self, request):
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('users:home'))
        else:
            messages.error(request, "Invalid username or password")
            return HttpResponseRedirect(reverse('users:register'))


class LoginView(View):
    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('users:home'))
        else:
            messages.error(request, "Invalid username or password")
            return HttpResponseRedirect(reverse('users:login'))

    def get(self, request):
        form = AuthenticationForm()
        return render(request, "users/login.html", {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('users:login'))


@method_decorator(login_required, name='dispatch')
class ProfileUpdateView(View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        profile_update_form = ProfileUpdateForm(instance=request.user.profile)
        return render(request, 'users/profile_update.html',
                      {'user_update_form': user_update_form, 'profile_update_form': profile_update_form})

    def post(self, request):
        user_update_form = UserUpdateForm(request.POST, instance=request.user)
        profile_update_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_update_form.is_valid() and profile_update_form.is_valid():
            user_update_form.save()
            profile_update_form.save()
            messages.success(request, "Your profile has been updated!")
            return HttpResponseRedirect(reverse('users:profile', args=[request.user.username]))
        else:
            messages.error(request, "Please try to update again.")
            return HttpResponseRedirect(reverse('users:profile_update'))


class ProfileView(View):
    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        now_year = timezone.now().year

        all_liked_movies = LikedMovie.objects.filter(user=user)
        liked_movies = all_liked_movies.order_by('-like_date', 'movie__title')[:4]
        liked_this_year_count = all_liked_movies.filter(like_date__year=now_year).count()
        all_liked_count = all_liked_movies.count()

        all_want_to_watch = WantToWatchMovie.objects.filter(user=user)
        want_to_watch = all_want_to_watch.order_by('-want_to_date', 'movie__title')[:4]

        all_watched_movies = WatchedMovie.objects.filter(user=user)
        watched_movies = all_watched_movies.order_by('-watch_date', 'movie__title')[:4]
        watched_this_year_count = all_watched_movies.filter(watch_date__year=now_year).count()
        all_watched_count = all_watched_movies.count()

        reviews_this_year_count = Review.objects.filter(writer=user, review_date__year=now_year).count()
        all_reviews_count = Review.objects.filter(writer=user).count()

        are_equal = request.user.username == username

        follows = (request.user.is_authenticated and Following.objects.filter(follower=request.user,
                                                                              following=user).exists())

        mutual_follow = (request.user.is_authenticated and Following.objects.filter(follower=request.user,
                                                                                    following=user).exists() and
                         Following.objects.filter(follower=user, following=request.user).exists())

        mutual_follow_or_equal = mutual_follow or are_equal
        followers_count = user.followers.count()
        following_count = user.followings.count()

        most_liked_lists = ListName.objects.filter(user=user, is_private=False).order_by("-likes", "name")[:3]

        return render(request, 'users/profile.html', {'liked_movies': liked_movies, 'want_to_watch': want_to_watch,
                                                      "user": user, "are_equal": are_equal, "follows": follows,
                                                      "mutual_follow_or_equal": mutual_follow_or_equal,
                                                      "followers_count": followers_count,
                                                      "following_count": following_count,
                                                      "watched_movies": watched_movies,
                                                      "all_watched_count": all_watched_count,
                                                      "watched_this_year_count": watched_this_year_count,
                                                      "reviews_this_year_count": reviews_this_year_count,
                                                      "all_reviews_count": all_reviews_count,
                                                      "all_liked_count": all_liked_count,
                                                      "liked_this_year_count": liked_this_year_count,
                                                      "year": now_year, "most_liked_lists": most_liked_lists})


class LikedMovieView(View):
    def get(self, request, username, year=0):
        user = get_object_or_404(User, username=username)
        if year == 0:
            movies = user.likedmovie_set.all().order_by('-like_date', 'movie__title')
        else:
            movies = user.likedmovie_set.filter(like_date__year=year).order_by('-like_date', 'movie__title')
        paginator = Paginator(movies, 24)
        page_number = request.GET.get('page')
        liked_movies = paginator.get_page(page_number)
        are_equal = request.user.username == username
        years = LikedMovie.objects.filter(user=user).values_list("like_date__year", flat=True).distinct().order_by(
            "-like_date__year")
        return render(request, 'users/liked_movies.html', {"liked_movies": liked_movies, "user": user,
                                                           "are_equal": are_equal, "year": year,
                                                           "all": year == 0, "years": years})


class WatchListView(View):
    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        paginator = Paginator(user.wanttowatchmovie_set.all().order_by('-want_to_date', 'movie__title'), 24)
        page_number = request.GET.get('page')
        watch_list = paginator.get_page(page_number)
        are_equal = request.user.username == username
        return render(request, 'users/watchlist_movies.html', {"watch_list": watch_list, "user": user,

users/templates/users/all_followers.html
{% extends "users/base.html" %}

{% block title %}
    {% if are_equal %}
        Your Followers
    {% else %}
        All Followers of {{ user.username }}
    {% endif %}
{% endblock %}

{% block content %}
    {% if messages %}
        <div class="alert alert-info">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    {% if permitted %}
    <div class="container mt-4 mb-4">
        <h2 class="mb-3">
            {% if are_equal %}
                You have {{ followers_count }} followers.
            {% else %}
                {{ user.username }} has {{ followers_count }} followers.
            {% endif %}
        </h2>
        {% if followers %}
            <div class="list-group">
                {% for follower in followers %}
                    <a href="{% url 'users:profile' follower.follower.username %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                        <span class="d-flex align-items-center">
                            {{ follower.follower.username }}
                        </span>
                        <div class="d-flex align-items-center ms-auto">
                            <span class="badge bg-secondary rounded-pill me-2">Profile</span>
                            {% if request.user.is_authenticated and are_equal %}
                                <form action="{% url 'users:delete_follower' %}" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <input type="hidden" name="selected_follower" value="{{ follower.follower.username }}">
                                    <button type="submit" class="btn btn-outline-danger btn-sm" onclick="return confirm('Are you sure you want to delete this user from your followers?');" title="Remove follower">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </form>
                            {% endif %}
                        </div>
                    </a>
                {% endfor %}
            </div>
        {% else %}
            <p class="text-center">No followers yet.</p>
        {% endif %}
    </div>
    {% endif %}
{% endblock %}

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}MovieNarts{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }
        body {
            display: flex;
            flex-direction: column;
        }
        .content {
            flex: 1;
        }
        .navbar {
            background-color: #000000;
        }
        .navbar-brand {
            color: #ffffff;
        }
        .navbar-nav .nav-link {
            color: #ffffff;
        }
        .navbar-nav .nav-link:hover {
            color: #ff5722;
        }
        .form-control {
            border: 1px solid #ff5722;
            border-radius: 0.25rem;
            padding: 0.375rem 0.75rem;
        }
        .form-control:focus {
            border-color: #ff5722;
            box-shadow: 0 0 0 0.2rem rgba(255, 87, 34, 0.25);
        }
        .btn-outline-success {
            border-color: #ff5722;
            color: #ff5722;
        }
        .btn-outline-success:hover {
            background-color: #ff5722;
            color: #ffffff;
        }
        footer {
            background-color: #121212;
            color: #ffffff;
            padding: 20px 0;
        }
        .footer-links a {
            color: #ffffff;
        }
        .footer-links a:hover {
            color: #ff5722;
        }
        /* Add this to your custom CSS file or inside a <style> block in your base template */
        .username-link {
            color: inherit; /* Inherit color from parent element */
            text-decoration: none; /* Remove underline */
            transition: color 0.3s, text-decoration 0.3s; /* Smooth transition for hover effect */
        }

        .username-link:hover {
            color: #007bff; /* Change color on hover to indicate clickability */
            text-decoration: underline; /* Add underline on hover */
        }
        .card-custom {
            max-width: 200px; /* Set the maximum width for the card */
            height: auto; /* Allow the card height to adjust automatically */
            margin: auto; /* Center the card horizontally */
        }

        .card-img-top-custom {
            max-width: 100%; /* Ensure the image fits within the card */
            height: auto; /* Maintain aspect ratio of the image */
        }

        .like-unlike-btn {
            font-size: 24px;
            color: #888;
            background: none;
            border: none;
            cursor: pointer;
        }

        .more-link {
            font-size: 36px;
            color: #343a40; /* light color to match the dark theme */
            text-decoration: none;
            transition: transform 0.2s ease, color 0.2s ease;
            margin-left: 7px;
        }

        .more-link:hover {
            transform: scale(1.2); /* scale effect on hover */
            color: #ff5722; /* highlight color on hover */
        }

        .dropdown-menu {
            max-height: 10rem; /* Adjust this value to fit approximately 6 options */
            overflow-y: auto; /* Enable vertical scrolling if there are more options */
        }

        #trailerModal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1050; /* Ensure it's above other content */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgba(0,0,0,0.5); /* Black w/ opacity */
        }

        .modal-content-1 {
            background-color: rgb(0, 0, 0);
            margin: 10% auto; /* Center the modal */
            padding: 20px;
            border: 1px solid #888;
            width: 50%; /* Adjust as needed */
            position: relative; /* For absolute positioning of the close button */
            border-radius: 15px; /* Rounded corners */
            display: flex; /* Use flexbox to center the content */
            justify-content: center; /* Horizontally center content */
            align-items: center; /* Vertically center content */
        }

        .close {
            position: absolute;
            top: 10px;
            right: 15px;
            color: red;
            font-size: 50px;
            font-weight: bold;
            cursor: pointer;
        }

        .close:hover,
        .close:focus {
            color: darkred;
            text-decoration: none;
            cursor: pointer;
        }

        #trailerIframe {
            max-width: 100%; /* Ensure the iframe does not overflow */
            max-height: 100%; /* Ensure the iframe does not overflow */
            border-radius: 10px; /* Rounded corners for iframe */
        }

        .btn-red {
            background-color: #b80101; /* Red background */
            color: #fff; /* White text */
            border: none; /* Remove border */
            font-size: 16px; /* Adjust font size */
            padding: 10px 20px; /* Add padding */
            border-radius: 5px; /* Rounded corners */
            display: flex; /* Align items */
            align-items: center; /* Center items vertically */
            gap: 8px; /* Space between icon and text */
        }

        .btn-red i {
            font-size: 20px; /* Adjust icon size */
        }

        /* Hover effect */
        .btn-red:hover {
            background-color: darkred; /* Darker red on hover */
            text-decoration: none;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'users:home' %}">MovieNarts</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:home' %}">Home</a>
                    </li>
                    <!-- Dropdown Menu for Genres and Years -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="browseDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            All Movies
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="browseDropdown">
                            <li><a class="dropdown-item" href="{% url 'users:all_genres' %}">Browse by Genre</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:movies_of_year' 2024 %}">Browse by Year</a></li>
                        </ul>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:profile' request.user.username %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                        </li>
                    {% endif %}
                    <!-- Add more links as needed -->
                </ul>
                <!-- Search Form -->
                <form action="{% url 'users:search' %}" class="d-flex" role="search" method="POST">
                    {% csrf_token %}
                    <input
                        class="form-control me-2"
                        type="search"
                        placeholder="Search movies, lists and more"
                        name="search_query"
                        required
                        aria-label="Search"
                    >
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="content">
        <main class="container mt-4">
            {% block content %}
            <!-- Default content or messages go here -->
            {% endblock %}
        </main>
    </div>

    <!-- Footer -->
    <footer class="text-center">
        <div class="container">
            <div class="footer-links">
                <!-- Footer links can be added here -->
            </div>
            <p class="mt-3">&copy; 2024 MovieNarts. All rights reserved.</p>
        </div>
    </footer>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Custom JS -->
    <!--<script src="{<% static 'js/scripts.js' %}"></script>-->

</body>
</html>

users/templates/users/favourite_lists.html
{% extends "users/base.html" %}

{% block title %}
    {% if are_equal %}
        Your Favourite Lists
    {% else %}
        Favourite Lists of {{ user.username }}
    {% endif %}
{% endblock %}

{% block content %}
    {% if messages %}
        <div class="alert alert-info">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h4>
                    {% if are_equal %}
                        Your Favourite Lists
                    {% else %}
                        Favourite Lists of <a href="{% url 'users:profile' user.username %}" class="username-link">{{ user.username }}</a>
                    {% endif %}
                </h4>
            </div>

            <!-- List of all lists -->
            <div class="list-group">
                {% if lists %}
                    {% for list in lists %}
                        <a href="{% url 'users:custom_list' list.list_name.id list.list_name.user.username%}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            {{ list.list_name.name }}
                            <span class="badge bg-secondary rounded-pill">View</span>
                        </a>
                    {% endfor %}
                {% else %}
                    {% if are_equal %}
                        <p>No favourite lists. Like a new list to get started.</p>
                    {% else %}
                        <p>No favourite lists.</p>
                    {% endif%}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends "users/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card border-dark shadow-lg">
                <div class="card-header bg-dark text-white text-center">
                    <h2>Login</h2>
                </div>
                <div class="card-body">
                    <!-- Displaying Messages -->
                    {% if messages %}
                        <div class="alert alert-warning" role="alert">
                            <ul class="mb-0">
                                {% for message in messages %}
                                    <li>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}

                    <!-- Login Form -->
                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            {{ form.as_p }}
                        </div>
                        <div class="d-grid gap-2 text-center">
                            <button type="submit" class="btn btn-primary btn-lg">Login</button>
                        </div>
                    </form>

                    <!-- Registration Link -->
                    <div class="mt-3 text-center">
                        <p>Don't have an account?</p>
                        <a href="{% url 'users:register' %}" class="btn btn-secondary btn-sm">Register Now!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}